name: Build and Push Docker image

on:
  push:
    branches:
      - main  # pornește la push pe ramura main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/shop_26:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/shop_26:latest
